services:
  web2md:
    image: ghcr.io/lucanori/web2md:latest
    container_name: web2md
    networks:
      - web2md
    ports:
      - "7001:8000"
    depends_on:
      - searxng
      - browserless
    environment:
      - SEARXNG_URL=${SEARXNG_URL}
      - BROWSERLESS_URL=${BROWSERLESS_URL}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
      - MAX_IMAGES_PER_SITE=${MAX_IMAGES_PER_SITE}
      - MIN_IMAGE_SIZE=${MIN_IMAGE_SIZE}
      - MAX_TOKENS_PER_REQUEST=${MAX_TOKENS_PER_REQUEST}
      - FILTER_SEARCH_RESULT_BY_AI=${FILTER_SEARCH_RESULT_BY_AI}
      - AI_API_KEY=${AI_API_KEY}
      - AI_MODEL=${AI_MODEL}
      - AI_BASE_URL=${AI_BASE_URL}
    
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - web2md
    volumes:
      - ./searxng:/etc/searxng:rw

  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium
    restart: unless-stopped
    networks:
      - web2md
    environment:
      - TOKEN=${BROWSERLESS_TOKEN}
      - MAX_CONCURRENT_SESSIONS=10
      - TIMEOUT=60000
      - QUEUED=10

networks:
  web2md:
    driver: bridge