services:
  web2md:
    image: ghcr.io/lucanori/web2md:rolling
    container_name: web2md
    networks:
      - web2md
    ports:
      - "7001:8000"
    depends_on:
      - searxng
      - browserless
    environment:
      - SEARXNG_URL=${SEARXNG_URL}
      - BROWSERLESS_URL=${BROWSERLESS_URL}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN}
      - REQUEST_TIMEOUT=30
      - MAX_IMAGES_PER_SITE=0
      - MIN_IMAGE_SIZE=256
      - MAX_TOKENS_PER_REQUEST=100000
      - FILTER_SEARCH_RESULT_BY_AI=true
      - AI_API_KEY=${WEB2MD_LLM_API_KEY}
      - AI_MODEL=google/gemini-2.5-flash
      - AI_BASE_URL=https://openrouter.ai/api/v1
    
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - web2md
    ports:
      - "7002:8080"
    volumes:
      - ./searxng:/etc/searxng:rw

  browserless:
    container_name: browserless
    image: ghcr.io/browserless/chromium
    restart: unless-stopped
    networks:
      - web2md
    ports:
      - "7003:3000"
    environment:
      - TOKEN=${BROWSERLESS_TOKEN}
      - MAX_CONCURRENT_SESSIONS=10
      - TIMEOUT=60000
      - QUEUED=10

networks:
  web2md:
    driver: bridge