services:
  web2md-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2md-dev
    ports:
      - "7001:8000"
    volumes:
      - ..:/app:rw
      - /app/.venv
    environment:
      - SEARXNG_URL=http://searxng-dev:8080
      - BROWSERLESS_URL=http://browserless-dev:3000
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN}
      - REQUEST_TIMEOUT=30
      - MAX_IMAGES_PER_SITE=0
      - MIN_IMAGE_SIZE=256
      - MAX_TOKENS_PER_REQUEST=100000
      - FILTER_SEARCH_RESULT_BY_AI=true
      - AI_API_KEY=${WEB2MD_LLM_API_KEY}
      - AI_MODEL=google/gemini-2.5-flash
      - AI_BASE_URL=https://openrouter.ai/api/v1
      - AUTO_MAX_REQUESTS=5
      - AUTO_MAX_CONTEXT_TOKENS=850000
      - DB_CLEANUP_RETENTION_DAYS=90
      - DB_PATH=/app/data/web2md.db
    restart: unless-stopped
    networks:
      - web2md-dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  searxng-dev:
    container_name: searxng-dev
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - web2md-dev
    volumes:
      - ../searxng:/etc/searxng:rw

  browserless-dev:
    container_name: browserless-dev
    image: ghcr.io/browserless/chromium
    restart: unless-stopped
    networks:
      - web2md-dev
    environment:
      - TOKEN=${BROWSERLESS_TOKEN}
      - MAX_CONCURRENT_SESSIONS=10
      - TIMEOUT=60000
      - QUEUED=10

networks:
  web2md-dev:
    driver: bridge